# Generated by Django 3.1.5 on 2021-12-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=40)),
                ('cur_text', models.CharField(max_length=40)),
                ('cur_sym', models.CharField(max_length=40)),
                ('base_color', models.CharField(max_length=40)),
                ('secure_password', models.BooleanField(default=0)),
                ('agree_policy', models.BooleanField(default=0)),
                ('registration', models.BooleanField(default=0)),
                ('force_ssl', models.BooleanField(default=0)),
                ('logo', models.ImageField(upload_to='images/')),
                ('icon', models.ImageField(upload_to='images/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
